#for convenience, define variable $(OBJS) to list of object files                                                  
OBJS= simple_ui.o

#make has a "default rule" specifying how to build a an "object" file (.o) from a C source file (.c)               
#this rule includes $(CFLAGS) as one of cc's parameters                                                 
CFLAGS=-g -O3 # -g for debug, -O3 for optimization                                                                  

#first target is built by default.  Usually named "all"                                                            
all: ui

#ui (target) depends on all object files (prerequisites)                                                    
ui: $(OBJS)
	cc -o ui $(CFLAGS) $(OBJS)


#deletes files generated by compilation                                                                            
clean:
	rm -f *.o ui

run:ui
	./ui

